"""
Schemas package for HelpPet API.
Contains all Pydantic models and validation schemas.
"""

from .pet_schemas import (
    PetSpecies,
    PetGender,
    PetBase,
    PetCreate,
    PetUpdate,
    PetOwnerSummary,
    PetResponse,
    PetWithOwnerResponse,
    PetListResponse,
    PetSearchRequest,
)

from .medical_record_schemas import (
    MedicalRecordType,
    MedicalRecordBase,
    MedicalRecordCreate,
    MedicalRecordUpdate,
    PetSummary,
    VeterinarianSummary,
    MedicalRecordResponse,
    MedicalRecordWithRelationsResponse,
    MedicalRecordListResponse,
    MedicalRecordSearchRequest,
    MedicalRecordTimelineResponse,
    MedicalRecordStatsResponse,
    MEDICAL_DATA_TEMPLATES,
)

from .base import (
    BaseResponse,
    ErrorResponse,
    HealthResponse,
    ItemBase,
    ItemCreate,
    ItemUpdate,
    ItemResponse,
    RAGQueryRequest,
    SourceReference,
    RAGResponse,
)

from .scheduling_schemas import (
    AvailabilityType,
    ConflictType,
    ConflictSeverity,
    PracticeHoursCreate,
    PracticeHoursUpdate,
    PracticeHoursResponse,
    VetAvailabilityCreate,
    VetAvailabilityUpdate,
    VetAvailabilityResponse,
    RecurringAvailabilityCreate,
    RecurringAvailabilityUpdate,
    RecurringAvailabilityResponse,
    AppointmentConflictCreate,
    AppointmentConflictUpdate,
    AppointmentConflictResolve,
    AppointmentConflictResponse,
    AvailableSlotRequest,
    AvailableSlot,
    AvailableSlotsResponse,
    ConflictCheckRequest,
    ConflictCheckResponse,
    BulkPracticeHoursCreate,
    BulkRecurringAvailabilityCreate,
    ConflictStatistics,
    SchedulingStatistics,
)

__all__ = [
    # Pet schemas
    "PetSpecies",
    "PetGender",
    "PetBase",
    "PetCreate",
    "PetUpdate",
    "PetOwnerSummary",
    "PetResponse",
    "PetWithOwnerResponse",
    "PetListResponse",
    "PetSearchRequest",
    
    # Medical record schemas
    "MedicalRecordType",
    "MedicalRecordBase",
    "MedicalRecordCreate",
    "MedicalRecordUpdate",
    "PetSummary",
    "VeterinarianSummary",
    "MedicalRecordResponse",
    "MedicalRecordWithRelationsResponse",
    "MedicalRecordListResponse",
    "MedicalRecordSearchRequest",
    "MedicalRecordTimelineResponse",
    "MedicalRecordStatsResponse",
    "MEDICAL_DATA_TEMPLATES",
    
    # Base schemas
    "BaseResponse",
    "ErrorResponse",
    "HealthResponse",
    "ItemBase",
    "ItemCreate",
    "ItemUpdate",
    "ItemResponse",
    "RAGQueryRequest",
    "SourceReference",
    "RAGResponse",
    
    # Scheduling schemas
    "AvailabilityType",
    "ConflictType",
    "ConflictSeverity",
    "PracticeHoursCreate",
    "PracticeHoursUpdate",
    "PracticeHoursResponse",
    "VetAvailabilityCreate",
    "VetAvailabilityUpdate",
    "VetAvailabilityResponse",
    "RecurringAvailabilityCreate",
    "RecurringAvailabilityUpdate",
    "RecurringAvailabilityResponse",
    "AppointmentConflictCreate",
    "AppointmentConflictUpdate",
    "AppointmentConflictResolve",
    "AppointmentConflictResponse",
    "AvailableSlotRequest",
    "AvailableSlot",
    "AvailableSlotsResponse",
    "ConflictCheckRequest",
    "ConflictCheckResponse",
    "BulkPracticeHoursCreate",
    "BulkRecurringAvailabilityCreate",
    "ConflictStatistics",
    "SchedulingStatistics",
]
