"""create_visits_table_properly

Revision ID: 04240cf2bf54
Revises: 59035bb5b032
Create Date: 2025-08-31 12:51:11.898135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04240cf2bf54'
down_revision: Union[str, Sequence[str], None] = '59035bb5b032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('vet_user_id', sa.UUID(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('audio_transcript_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['veterinary_practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_pet_id'), 'visits', ['pet_id'], unique=False)
    op.create_index(op.f('ix_visits_practice_id'), 'visits', ['practice_id'], unique=False)
    op.create_index(op.f('ix_visits_state'), 'visits', ['state'], unique=False)
    op.create_index(op.f('ix_visits_vet_user_id'), 'visits', ['vet_user_id'], unique=False)
    op.create_index(op.f('ix_visits_visit_date'), 'visits', ['visit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visit_date'), table_name='visits')
    op.drop_index(op.f('ix_visits_vet_user_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_state'), table_name='visits')
    op.drop_index(op.f('ix_visits_practice_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_pet_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
