"""add_medical_records_table

Revision ID: 1b232ec1215f
Revises: 20265d085ccc
Create Date: 2025-08-29 20:14:30.999117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b232ec1215f'
down_revision: Union[str, Sequence[str], None] = '20265d085ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('medical_data', sa.JSON(), nullable=True),
    sa.Column('visit_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('veterinarian_name', sa.String(length=100), nullable=True),
    sa.Column('clinic_name', sa.String(length=100), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('medications', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_records_created_by_user_id'), 'medical_records', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_medical_records_is_current'), 'medical_records', ['is_current'], unique=False)
    op.create_index(op.f('ix_medical_records_pet_id'), 'medical_records', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_records_pet_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_is_current'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_created_by_user_id'), table_name='medical_records')
    op.drop_table('medical_records')
    # ### end Alembic commands ###
