"""add_appointments_tables

Revision ID: 927f6fc5a84b
Revises: 04240cf2bf54
Create Date: 2025-08-31 13:11:56.573624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927f6fc5a84b'
down_revision: Union[str, Sequence[str], None] = '04240cf2bf54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('pet_owner_id', sa.UUID(), nullable=False),
    sa.Column('assigned_vet_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_vet_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['veterinary_practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_assigned_vet_user_id'), 'appointments', ['assigned_vet_user_id'], unique=False)
    op.create_index(op.f('ix_appointments_pet_owner_id'), 'appointments', ['pet_owner_id'], unique=False)
    op.create_index(op.f('ix_appointments_practice_id'), 'appointments', ['practice_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('appointment_pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'pet_id', name='unique_appointment_pet')
    )
    op.create_index(op.f('ix_appointment_pets_appointment_id'), 'appointment_pets', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_pets_pet_id'), 'appointment_pets', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_pets_pet_id'), table_name='appointment_pets')
    op.drop_index(op.f('ix_appointment_pets_appointment_id'), table_name='appointment_pets')
    op.drop_table('appointment_pets')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_practice_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_pet_owner_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_assigned_vet_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
