"""add_pet_id_to_recordings_and_appointment_id_to_visits

Revision ID: fix_pet_recording_association
Revises: f1a2b3c4d5e6
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fix_pet_recording_association'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add pet_id to recordings table (CRITICAL FIX)
    op.add_column('recordings', sa.Column('pet_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_recordings_pet_id'), 'recordings', ['pet_id'], unique=False)
    op.create_foreign_key('fk_recordings_pet_id', 'recordings', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    
    # Add appointment_id to visits table for full context
    op.add_column('visits', sa.Column('appointment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_visits_appointment_id'), 'visits', ['appointment_id'], unique=False)
    op.create_foreign_key('fk_visits_appointment_id', 'visits', 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove appointment_id from visits
    op.drop_constraint('fk_visits_appointment_id', 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_appointment_id'), table_name='visits')
    op.drop_column('visits', 'appointment_id')
    
    # Remove pet_id from recordings
    op.drop_constraint('fk_recordings_pet_id', 'recordings', type_='foreignkey')
    op.drop_index(op.f('ix_recordings_pet_id'), table_name='recordings')
    op.drop_column('recordings', 'pet_id')
    
    # ### end Alembic commands ###
