"""Add specialties field to veterinary_practices

Revision ID: cabc51edb8e7
Revises: 3e909653104d
Create Date: 2025-08-29 16:24:17.229591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabc51edb8e7'
down_revision: Union[str, Sequence[str], None] = '3e909653104d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('veterinary_practices', sa.Column('specialties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('veterinary_practices', 'specialties')
    # ### end Alembic commands ###
